check/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ncloud.views_ai_app import *
from ncloud.views_iaas import *
from ncloud.views import *
from ncloud.API_List import *

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [

    url(r'^api/$', index, name='index'),

    # AI / Application
    url(r'^CSS$', CSS, name='CSS'),
    url(r'^nShortURLTest$', nShortURLTest, name='nShortURLTest'),
    url(r'^mapsTest$', mapsTest, name='mapsTest'),

    url(r'^api/ai_clova$', Clova, name='Clova'),
    url(r'^api/Maps$', Maps, name='Maps'),
    url(r'^api/Papago$', Papago, name='Papago'),
    url(r'^api/nShortURL$', nShortURL, name='nShortURL'),
    url(r'^api/CAPTCHA$', CAPTCHA, name='CAPTCHA'),
    url(r'^api/CAPTCHA_Check$', CAPTCHA_Check, name='CAPTCHA_Check'),
    url(r'^api/SearchTrend$', SearchTrend, name='SearchTrend'),
    url(r'^api/APIGW/$', APIGW, name='APIGW'),

    # PasS
    url(r'^api/geoLocation/$', geoLocation, name='geoLocation'),

    # IaaS
    url(r'^api/(?P<category>[a-z]+)/(?P<service>[a-zA-Z]+)/$', ServiceUrl, name='ServiceUrl'),
    url(r'^api/IaaS$', IaaS, name='IaaS'),

    # URL List
    url(r'^api/IaaS_API$', IaaS_API, name='IaaS_API'),
    url(r'^api/PaaS_API$', PaaS_API, name='PaaS_API'),
    url(r'^api/App_API$', App_API, name='App_API'),

]

learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learning_log.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^ncloud/', include('check.urls', namespace='ncloud')),
]

check/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models


class NaverApiStatus(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_type = models.CharField(max_length=20, blank=True, null=True)
    api_status = models.IntegerField(blank=True, null=True)
    api_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_status'


class NaverApiErrorLog(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_error_code = models.CharField(max_length=50, blank=True, null=True)
    api_error_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_error_log'

check/views.py
from django.shortcuts import render
from django.http import HttpResponse
from urllib.error import HTTPError, URLError
from django.views.decorators.csrf import csrf_exempt
import os, sys, ast, json, time, base64, hmac, hashlib
import urllib.request


@csrf_exempt
def ServiceUrl(request, category, service):
    return render(request, 'ncloud/' + category + '/' + service + '.html')

@csrf_exempt
def Hmac_Ajax(request, uri):
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    api_key = request.POST.get("api_key")
    access_key = request.POST.get("access_key")
    secret_key = request.POST.get("secret_key")
    secret_key = bytes(secret_key, 'UTF-8')

    method = "GET"
    if uri == '/api-test/v1/api':
        url = "https://ta50do4nv5.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + access_key
        sig = "x-ncp-apigw-signature-v2"
    else:
        url = "https://ncloud.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + api_key + "\n" + access_key
        sig = "x-ncp-apigw-signature-v1"
    message = bytes(message, 'UTF-8')
    signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
    sig_key = signingKey.decode('utf-8')

    req = urllib.request.Request(url)
    req.add_header("X-ncp-apigw-timestamp", timestamp)
    req.add_header("x-ncp-apigw-api-key", api_key)
    req.add_header("x-ncp-iam-access-key", access_key)
    req.add_header(sig, sig_key)
    res = urllib.request.urlopen(req)

    return res


@csrf_exempt
def App_Ajax(request, url):
    client_id = request.POST.get("client_id")
    client_secret = request.POST.get("client_secret")
    req = urllib.request.Request(url)
    req.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    req.add_header("X-NCP-APIGW-API-KEY",client_secret)
    return req


@csrf_exempt
def IaaS(request):
    rescode = "잘못된 method 입니다."
    rtnVal = {'rescode': rescode}
    if request.method=='POST':
        uri = request.POST.get("uri")
        api_list = request.POST.get("url_list")

        if request.POST.get("query") == None:
            qstring = ""
        else:
            qstring = request.POST.get("query")

        if '?' in api_list:
            queryCon = "&"
        else:
            queryCon = "?"
        uri = uri + api_list + queryCon + 'responseFormatType=json&' + qstring

        url = 'https://ncloud.apigw.ntruss.com' + uri
        try:
            res = Hmac_Ajax(request, uri)
        except URLError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        except HTTPError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        else:
            rescode = res.getcode()
        if(rescode == 200):
            response_body = res.read()
            result = response_body.decode()
            result = result[2:-1]
            rtnVal = {"rescode": rescode, "result": result}
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
        else:
            rtnVal = {"rescode": rescode}
            print("Error Code:" + rescode)
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
    else:
        return HttpResponse(json.dumps(rtnVal), content_type='application/json')

check/templates/ncloud/ai_application/api_gateway.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul>
<br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>API Gateway</h4>
    </div>
    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 20px 20px 20px 0px">
                <span style="margin: 10px 0 0 30px">
                  Access Key &nbsp;&nbsp;&nbsp; <input type="text" name="access_key" id="access_key" placeholder="Access Key"/>
                  </span>
                  <span style="margin: 10px 0 0 30px">
                    Secret Key &nbsp;&nbsp;&nbsp; <input type="text" name="secret_key" id="secret_key" placeholder="Secret Key"/>
                  </span><br><br>
                  <span style="margin: 10px 0 0 30px">
                    API Key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="api_key" id="api_key" placeholder="API Key"/>
                    </span>&nbsp;&nbsp;&nbsp;
                  <span style="margin: 10px 0 0 30px">
                    URL &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="url_value" id="url_value" placeholder="API Gateway URL"/>
                  </span>

                <span style="margin: 10px 0 0 30px"> &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>API Gateway Result</h4><br>
    </div>
    <pre id="result_area">
      <div class="box-header with-border" style="margin: 10px 0 0 10px"></div>
    </pre>
  </div>
</div>
<script type="text/javascript">

  $("#testBtn").click(function(){
    if ($("#api_key").val() == ""){
      alert("api_key 값을 입력해 주세요.");
      return $("#api_key").focus();

    }
    if ($("#access_key").val() == ""){
      alert("access_key 값을 입력해 주세요.");
      return $("#access_key").focus();
    }
    if ($("#secret_key").val() == ""){
      alert("secret_key 값을 입력해 주세요.");
      return $("#secret_key").focus();
    }
    if ($("#url_value").val() == ""){
      alert("url_value 값을 입력해 주세요.");
      return $("#url_value").focus();
    }

    $.ajax({
      type: "POST",
      async: false,
      url: "{% url 'ncloud:APIGW' %}",
      data: {'api_key':$("#api_key").val(), 'access_key':$("#access_key").val(), 'secret_key':$("#secret_key").val(), 'url_value':$("#url_value").val()},
      dataType: "json",
      success: function(data){
        $("#result_area").html("rescode : " + data.rescode);
        $("#result_area").append("<br><br>url : " + data.url);
        $("#result_area").append("<br><br>uri : " + data.uri);
        if (data.rescode == 200){
          $("#result_area").val();
        }
      },
      error: function(request, status, error){
        alert(request.responseText);
      },
    });
  })

</script>

{% endblock content %}

check/templates/ncloud/ai_application/captcha.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul><br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <form method="post" name="form">
      {% csrf_token %}
      <div class="box-header with-border">
        <span style="margin: 10px 0 0 0px" class="dropdown">
          <select class="form-control btn-default" name="target" id="target" style="font-size: 18px" >
            <option value="">CAPTCHA API Select</option>
            <option value="IMG">CAPTCHA IMG</option>
            <option value="AUDIO">CAPTCHA AUDIO</option>
          </select>
        </span>
      </div>
      <div class="box-body">
        <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
          <div class="row">
            <div class="col-sm-12">
              <div style="margin: 20px 20px 20px 0px">
                <span style="margin: 10px 0 0 30px">
                  Client ID &nbsp;&nbsp;&nbsp; <input type="text" name="client_id" id="client_id" placeholder="Client Id"/>
                  </span>
                <span style="margin: 10px 0 0 30px">
                  Client Secret &nbsp;&nbsp;&nbsp; <input type="text" name="client_secret" id="client_secret" placeholder="Client secret"/>
                  </span>
                <span style="margin: 10px 0 0 30px"> &nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>CAPTCHA API Result</h4><br>
    </div>
  <pre>
<div id="result_area" class="box-header with-border" style="margin: 10px 0px 0px 10px"></div>
  </pre>
  </div>
</div>

<script type="text/javascript">

  var result;
  $("#testBtn").click(function(){
    if ($("#client_id").val() == ""){
      alert("client_id 값을 입력해 주세요.");
      return $("#client_id").focus();

    }
    if ($("#client_secret").val() == ""){
      alert("client_secret 값을 입력해 주세요.");
      return $("#client_secret").focus();
    }

    $.ajax({
      type: "POST",
      async: false,
      url: "{% url 'ncloud:CAPTCHA' %}",
      data: {'client_id':$("#client_id").val(), 'client_secret':$("#client_secret").val(), 'target':$("#target").val()},
      dataType: "json",
      success: function(data){
        $("#result_area").html("key rescode : " + data.key_rescode +"<br><br>");
        $("#result_area").append("img rescode : " + data.img_rescode +"<br><br>");
        if ($("#target").val()=='IMG') {
          $("#result_area").append("<img id='captchaImg' src='/media/captcha.jpg'><br><br>");
        }
        else if ($("#target").val() == 'AUDIO') {
          // $("#result_area").append("<audio controls autoplay style='background-color:white'><source src='/media/captcha.wav' type='audio/wav'></audio>");
          $("#result_area").append("<audio controls autoplay id='captchaImg'><source src='/media/captcha.wav' type='audio/wav'></audio>");
        }
        $("#result_area").append("<form method='post' name='form'>");
        $("#result_area").append("{% csrf_token %}")
        $("#result_area").append("<input type='text' name='cap_value' id='cap_value' placeholder='checkCaptcha'/> &nbsp;&nbsp;&nbsp;");
        $("#result_area").append("<input type='button' class='ui button huge' name='checkBtn' id='checkBtn' value='submit' style='height: 30px; width: 100px' />");
        $("#result_area").append("</form>");
        $("#result_area").append("<br><br>");

        $("#checkBtn").click(function(){
          $.ajax({
            type: "POST",
            async: false,
            url: "{% url 'ncloud:CAPTCHA_Check' %}",
            data: {'cap_value': $("#cap_value").val()},
            dataType: "json",
            success: function(data){
              result = data.result;
              $("#img_check").remove();
              $("#result_area").append("<span id='img_check'>CAPTCHA Confirm : " + data.result + "</span>")

              if(!result) {
                $.ajax({
                  type: "POST",
                  async: false,
                  url: "{% url 'ncloud:CAPTCHA' %}",
                  data: {'client_id':$("#client_id").val(), 'client_secret':$("#client_secret").val(), 'target':$("#target").val()},
                  dataType: "json",
                  success: function(data){
                    var d = new Date();
                    if ($("#target").val() == 'IMG') {
                      document.getElementById("captchaImg").src="/media/captcha.jpg?a=" + d.getTime();
                    }
                    else if ($("#target").val() == 'AUDIO') {
                      document.getElementById("captchaImg").src="/media/captcha.wav?a=" + d.getTime();
                    }
                  }
                })

              }
            },
            error: function(data){
              console.log("error");
              alert("새로고침");
            }
          })
        })
      },
      error: function(request, status, error){
        alert(request.responseText);
      },
    });
  })



</script>

{% endblock content %}

check/templates/ncloud/ai_application/clova.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul>
<br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Clova API</h4>
    </div>
    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 20px 20px 20px 0px">
                <span style="margin: 10px 0 0 30px">
                  Client ID &nbsp;&nbsp;&nbsp; <input type="text" name="client_id" id="client_id" placeholder="Client Id"/>
                  </span>
                <span style="margin: 10px 0 0 30px">
                  Client Secret &nbsp;&nbsp;&nbsp; <input type="text" name="client_secret" id="client_secret" placeholder="Client secret"/>
                  </span>
                <span style="margin: 10px 0 0 30px"> &nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Clova API Result</h4><br>
    </div>
<pre>
<div id="result_area" class="box-header with-border" style="margin: 10px 0 0 10px"></div><div id="download_area" class="box-header with-border" style="display:none; margin: 10px 0 0 10px">  <a href="/media/NAVER_TEST.mp3" download><h4>MP3 download</h4></a></div>
  </pre>
  </div>
</div>
<script type="text/javascript">

  $("#testBtn").click(function(){
    if ($("#client_id").val() == ""){
      alert("client_id 값을 입력해 주세요.");
      return $("#client_id").focus();

    }
    if ($("#client_secret").val() == ""){
      alert("client_secret 값을 입력해 주세요.");
      return $("#client_secret").focus();
    }

    $.ajax({
      type: "POST",
      async: false,
      url: "{% url 'ncloud:CSS' %}",
      data: {'client_id':$("#client_id").val(), 'client_secret':$("#client_secret").val()},
      dataType: "json",
      success: function(data){
        $("#result_area").html("rescode : " + data.rescode);
        if (data.rescode == 200){
          $("#download_area").css("display","block");
        }
      },
      error: function(request, status, error){
        alert(request.responseText);
      },
    });
  })

</script>

{% endblock content %}

check/templates/ncloud/ai_application/geoLocation.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul>
<br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>geoLocation</h4>
    </div>
    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 20px 20px 20px 0px">
                <span style="margin: 10px 0 0 30px">
                  Access Key &nbsp;&nbsp;&nbsp; <input type="text" name="access_key" id="access_key" placeholder="Access Key"/>
                  </span>
                  <span style="margin: 10px 0 0 30px">
                    Secret Key &nbsp;&nbsp;&nbsp; <input type="text" name="secret_key" id="secret_key" placeholder="Secret Key"/>
                  </span><br><br>
                  <span style="margin: 10px 0 0 30px">
                    API Key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="api_key" id="api_key" placeholder="API Key"/>
                    </span>&nbsp;&nbsp;&nbsp;
                  <span style="margin: 10px 0 0 30px">&nbsp;&nbsp;
                    IP &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="ip_value" id="ip_value" placeholder="IP"/>
                  </span>

                <span style="margin: 10px 0 0 30px"> &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>geoLocation Result</h4><br>
    </div>
    <pre id="result_area">
      <div class="box-header with-border" style="margin: 10px 0 0 10px"></div>
    </pre>
  </div>
</div>
<script type="text/javascript">

  $("#testBtn").click(function(){
    if ($("#api_key").val() == ""){
      alert("api_key 값을 입력해 주세요.");
      return $("#api_key").focus();
    }
    if ($("#access_key").val() == ""){
      alert("access_key 값을 입력해 주세요.");
      return $("#access_key").focus();
    }
    if ($("#secret_key").val() == ""){
      alert("secret_key 값을 입력해 주세요.");
      return $("#secret_key").focus();
    }
    if ($("#ip_value").val() == ""){
      alert("ip_value 값을 입력해 주세요.");
      return $("#ip_value").focus();
    }

    $.ajax({
      type: "POST",
      async: false,
      url: "{% url 'ncloud:geoLocation' %}",
      data: {'api_key':$("#api_key").val(), 'access_key':$("#access_key").val(), 'secret_key':$("#secret_key").val(), 'ip_value':$("#ip_value").val()},
      dataType: "json",
      success: function(data){
        $("#result_area").html("rescode : " + data.rescode);
        $("#result_area").append("<br><br>result : " + data.result);
        if (data.rescode == 200){
          $("#result_area").val();
        }
      },
      error: function(request, status, error){
        alert(request.responseText);
      },
    });
  })

</script>

{% endblock content %}

check/templates/ncloud/ai_application/maps.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul>
<br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Maps API</h4>
    </div>
    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 20px 20px 20px 0px">
                <span style="margin: 10px 0 0 30px">
                  Client ID &nbsp;&nbsp;&nbsp; <input type="text" name="client_id" id="client_id" placeholder="Client Id"/>
                  </span>
                <span style="margin: 10px 0 0 30px">
                  Client Secret &nbsp;&nbsp;&nbsp; <input type="text" name="client_secret" id="client_secret" placeholder="Client secret"/>
                  </span>
                  <span style="margin: 10px 0 0 30px">
                    EncText &nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="encText" id="encText" value="불정로 6">
                    </span>
                <span style="margin: 10px 0 0 30px"> &nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Maps API Result</h4><br>
    </div>
    <br>
    <pre id="result_area"></pre>

    <div class="box-header with-border" style="height:400px;" id="map"></div>
  </div>
</div>

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=7gdzqkcoua&submodules=geocoder"></script>


<script type="text/javascript">

  $("#testBtn").click(function(){
    if ($("#client_id").val() == ""){
      alert("client_id 값을 입력해 주세요.");
      return $("#client_id").focus();

    }
    if ($("#client_secret").val() == ""){
      alert("client_secret 값을 입력해 주세요.");
      return $("#client_secret").focus();
    }

    $.ajax({
      type: "POST",
      async: false,
      url: "{% url 'ncloud:mapsTest' %}",
      data: {'client_id':$("#client_id").val(), 'client_secret':$("#client_secret").val(), 'encText':$("#encText").val()},
      dataType: "json",
      success: function(data){



        $("#result_area").html("rescode : " + data.rescode);
        if (data.rescode == 200){
          var obj = JSON.parse(data.resval);

          showMap(obj.result.items[0].point.y, obj.result.items[0].point.x);
        }

      },
      error: function(request, status, error){
        alert(request.responseText);
      },
    });
  })

  function showMap(x,y){
    var map = new naver.maps.Map('map', {center: new naver.maps.LatLng(x, y)});

    var marker = new naver.maps.Marker({
        position: new naver.maps.LatLng(x, y),
        map: map
    });

  }


</script>

{% endblock content %}