check/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ncloud.views_ai_app import *
from ncloud.views_iaas import *
from ncloud.views import *
from ncloud.API_List import *

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [

    url(r'^api/$', index, name='index'),

    # AI / Application
    url(r'^CSS$', CSS, name='CSS'),
    url(r'^nShortURLTest$', nShortURLTest, name='nShortURLTest'),
    url(r'^mapsTest$', mapsTest, name='mapsTest'),

    url(r'^api/ai_clova$', Clova, name='Clova'),
    url(r'^api/Maps$', Maps, name='Maps'),
    url(r'^api/Papago$', Papago, name='Papago'),
    url(r'^api/nShortURL$', nShortURL, name='nShortURL'),
    url(r'^api/CAPTCHA$', CAPTCHA, name='CAPTCHA'),
    url(r'^api/CAPTCHA_Check$', CAPTCHA_Check, name='CAPTCHA_Check'),
    url(r'^api/SearchTrend$', SearchTrend, name='SearchTrend'),
    url(r'^api/APIGW/$', APIGW, name='APIGW'),

    # PasS
    url(r'^api/geoLocation/$', geoLocation, name='geoLocation'),

    # IaaS
    url(r'^api/(?P<category>[a-z]+)/(?P<service>[a-zA-Z]+)/$', ServiceUrl, name='ServiceUrl'),
    url(r'^api/IaaS$', IaaS, name='IaaS'),

    # URL List
    url(r'^api/IaaS_API$', IaaS_API, name='IaaS_API'),
    url(r'^api/PaaS_API$', PaaS_API, name='PaaS_API'),
    url(r'^api/App_API$', App_API, name='App_API'),

]

learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learning_log.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^ncloud/', include('check.urls', namespace='ncloud')),
]

check/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models


class NaverApiStatus(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_type = models.CharField(max_length=20, blank=True, null=True)
    api_status = models.IntegerField(blank=True, null=True)
    api_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_status'


class NaverApiErrorLog(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_error_code = models.CharField(max_length=50, blank=True, null=True)
    api_error_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_error_log'

check/views.py
from django.shortcuts import render
from django.http import HttpResponse
from urllib.error import HTTPError, URLError
from django.views.decorators.csrf import csrf_exempt
import os, sys, ast, json, time, base64, hmac, hashlib
import urllib.request


@csrf_exempt
def ServiceUrl(request, category, service):
    return render(request, 'ncloud/' + category + '/' + service + '.html')

@csrf_exempt
def Hmac_Ajax(request, uri):
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    api_key = request.POST.get("api_key")
    access_key = request.POST.get("access_key")
    secret_key = request.POST.get("secret_key")
    secret_key = bytes(secret_key, 'UTF-8')

    method = "GET"
    if uri == '/api-test/v1/api':
        url = "https://ta50do4nv5.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + access_key
        sig = "x-ncp-apigw-signature-v2"
    else:
        url = "https://ncloud.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + api_key + "\n" + access_key
        sig = "x-ncp-apigw-signature-v1"
    message = bytes(message, 'UTF-8')
    signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
    sig_key = signingKey.decode('utf-8')

    req = urllib.request.Request(url)
    req.add_header("X-ncp-apigw-timestamp", timestamp)
    req.add_header("x-ncp-apigw-api-key", api_key)
    req.add_header("x-ncp-iam-access-key", access_key)
    req.add_header(sig, sig_key)
    res = urllib.request.urlopen(req)

    return res


@csrf_exempt
def App_Ajax(request, url):
    client_id = request.POST.get("client_id")
    client_secret = request.POST.get("client_secret")
    req = urllib.request.Request(url)
    req.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    req.add_header("X-NCP-APIGW-API-KEY",client_secret)
    return req


@csrf_exempt
def IaaS(request):
    rescode = "잘못된 method 입니다."
    rtnVal = {'rescode': rescode}
    if request.method=='POST':
        uri = request.POST.get("uri")
        api_list = request.POST.get("url_list")

        if request.POST.get("query") == None:
            qstring = ""
        else:
            qstring = request.POST.get("query")

        if '?' in api_list:
            queryCon = "&"
        else:
            queryCon = "?"
        uri = uri + api_list + queryCon + 'responseFormatType=json&' + qstring

        url = 'https://ncloud.apigw.ntruss.com' + uri
        try:
            res = Hmac_Ajax(request, uri)
        except URLError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        except HTTPError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        else:
            rescode = res.getcode()
        if(rescode == 200):
            response_body = res.read()
            result = response_body.decode()
            result = result[2:-1]
            rtnVal = {"rescode": rescode, "result": result}
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
        else:
            rtnVal = {"rescode": rescode}
            print("Error Code:" + rescode)
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
    else:
        return HttpResponse(json.dumps(rtnVal), content_type='application/json')

check/templates/ncloud/iaas/autoscaling.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul><br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}" />
<div class="box">
  <div class="box-body">
    <div class="box-header with-border chk_hd" style="margin: 5px 5px 5px 10px">
      <div style="-webkit-flex:1; flex:1;"><h4>Auto Sacling</h4></div>
      <div class="checks etrans chk_all" ><input type="checkbox" id="checkall" /><label for="checkall">모두선택</label></div>
    </div>

    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 10px 20px 20px 0px">
                <div class="chk_hd">
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="1" name="chk[]" value="getLaunchConfigurationList" /><label for="1">론치설정 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="2" name="chk[]" value="getAutoScalingGroupList" /><label for="2">그룹 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="3" name="chk[]"  value="getScheduledActionList" /><label for="3">스케쥴액션 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="4" name="chk[]"  value="getScalingProcessTypeList" /><label for="4">프로세스 구분 리스트</label>
                    </div>
                </div>
                <div class="chk_hd">
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="6" name="chk[]" value="getAutoScalingActivityLogList" /><label for="6">액티비티 로그 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="7" name="chk[]" value="getAutoScalingConfigurationLogList" /><label for="7">오토스케일링 설정 로그 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="8" name="chk[]" value="getAutoScalingPolicyList" /><label for="8">오토스케일링 정책 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="9" name="chk[]" value="getAdjustmentTypeList" /><label for="9">조정유형 리스트</label>
                    </div>
                </div>

                <br/>

                <span class="recive">
                  Access Key &nbsp;&nbsp;&nbsp; <input type="text" name="access_key" id="access_key" placeholder="Access Key" value=" "/>
                  </span>
                  <span class="recive">
                    Secret Key &nbsp;&nbsp;&nbsp; <input type="text" name="secret_key" id="secret_key" placeholder="Secret Key" value=" "/>
                  </span><br><br>
                  <span class="recive">
                    API Key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="api_key" id="api_key" placeholder="API Key" value=" " />
                    </span>&nbsp;&nbsp;&nbsp;
                  <span class="recive">
                    Query &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="query" id="query" placeholder="Query string"/>
                  </span>
                <span class="recive"> &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Auto Sacling Result</h4><br>
    </div>

    <pre id="result_area">
      <div class="rescode" style="margin: 10px 0 0 10px; width:10px; height:10px;"></div>
    </pre>
  </div>
</div>

<div class="wrap-loading display-none" >
  <div class="loader"></div>
</div>

<script type="text/javascript">
$(document).ready( () => {
  $("#checkall").click( () => {
    if($("#checkall").prop("checked")){
      $("input[name='chk[]']").prop("checked", true);
    }else{
      $("input[name='chk[]']").prop("checked", false);
    }
  })
})

  $("#testBtn").click(function(){
    if ($("#api_key").val() == ""){
      alert("api_key 값을 입력해 주세요.");
      return $("#api_key").focus();
    }
    if ($("#access_key").val() == ""){
      alert("access_key 값을 입력해 주세요.");
      return $("#access_key").focus();
    }
    if ($("#secret_key").val() == ""){
      alert("secret_key 값을 입력해 주세요.");
      return $("#secret_key").focus();
    }
    if ( !$("input[name='chk[]']").is(":checked") ){
      alert("check.");
      return $("#checkall").focus();
    }

    var list = [];
    $("input[name='chk[]']:checked").each(function(){
      list.push($(this).val());
      $("#result_area").html("<div onclick='("+'$(".result").slideToggle("slow")'+")'>action : rescode ▼ </div><br/><br/>");
    })

    $('.wrap-loading').removeClass('display-none');

    setTimeout(function(){

      for (let key=0; key < list.length; key++){

      $.ajax({
        type: "POST",
        async: false,
        url: "{% url 'ncloud:IaaS' %}",
        data: {'uri':'/autoscaling/v1/', 'api_key':$("#api_key").val(), 'access_key':$("#access_key").val(), 'secret_key':$("#secret_key").val(), 'query':$("#query").val(), 'url_list': list[key] },
        dataType: "json",
        success: function(data){
          $("#result_area").append("<div class='rescode' id='"+ key +"' onclick='slide("+ key +")' style='cursor:pointer'>" + list[key] + " : " + data.rescode  + "</div>");
          $("#result_area").append("<textarea class='result' id='pannel" + key + "'>" + data.result + "</textarea>");
        },error: function(request, status, error){
          alert(request.responseText);
        },
      });

        if(key===(list.length - 1)){
          $('.wrap-loading').addClass('display-none');
        }
      }
    }, 100);
  });

  function slide(key){
    $("#pannel" + key).slideToggle("slow");
  }

</script>
{% endblock content %}

check/templates/ncloud/iaas/cdn.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul><br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}" />
<div class="box">
  <div class="box-body">
    <div class="box-header with-border chk_hd" style="margin: 5px 5px 5px 10px">
      <div style="-webkit-flex:1; flex:1;"><h4>CDN</h4></div>
      <div class="checks etrans chk_all" ><input type="checkbox" id="checkall" /><label for="checkall">모두선택</label></div>
    </div>

    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 10px 20px 20px 0px">
                <div class="chk_hd">
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="1" name="chk[]" value="getCdnPlusInstanceList" /><label for="1">CDN+ 인스턴스리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="2" name="chk[]" value="getGlobalCdnInstanceList" /><label for="2">Global CDN 인스턴스리스트</label>
                    </div>
                </div>

                <br/>

                <span class="recive">
                  Access Key &nbsp;&nbsp;&nbsp; <input type="text" name="access_key" id="access_key" placeholder="Access Key" value=" "/>
                  </span>
                  <span class="recive">
                    Secret Key &nbsp;&nbsp;&nbsp; <input type="text" name="secret_key" id="secret_key" placeholder="Secret Key" value=" "/>
                  </span><br><br>
                  <span class="recive">
                    API Key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="api_key" id="api_key" placeholder="API Key" value=" " />
                    </span>&nbsp;&nbsp;&nbsp;
                  <span class="recive">
                    Query &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="query" id="query" placeholder="Query string"/>
                  </span>
                <span class="recive"> &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>CDN Result</h4><br>
    </div>

    <pre id="result_area">
      <div class="rescode" style="margin: 10px 0 0 10px; width:10px; height:10px;"></div>
    </pre>
  </div>
</div>

<div class="wrap-loading display-none" >
  <div class="loader"></div>
</div>

<script type="text/javascript">
$(document).ready( () => {
  $("#checkall").click( () => {
    if($("#checkall").prop("checked")){
      $("input[name='chk[]']").prop("checked", true);
    }else{
      $("input[name='chk[]']").prop("checked", false);
    }
  })
})

  $("#testBtn").click(function(){
    if ($("#api_key").val() == ""){
      alert("api_key 값을 입력해 주세요.");
      return $("#api_key").focus();
    }
    if ($("#access_key").val() == ""){
      alert("access_key 값을 입력해 주세요.");
      return $("#access_key").focus();
    }
    if ($("#secret_key").val() == ""){
      alert("secret_key 값을 입력해 주세요.");
      return $("#secret_key").focus();
    }
    if ( !$("input[name='chk[]']").is(":checked") ){
      console.log($("input[name='chk[]']").is(":checked"))
      alert("check.");
      return $("#checkall").focus();
    }

    var list = [];
    $("input[name='chk[]']:checked").each(function(){
      list.push($(this).val());
      $("#result_area").html("<div onclick='("+'$(".result").slideToggle("slow")'+")'>action : rescode ▼ </div><br/><br/>");
    })

    $('.wrap-loading').removeClass('display-none');

    setTimeout(function(){

      for (let key=0; key < list.length; key++){

      $.ajax({
        type: "POST",
        async: false,
        url: "{% url 'ncloud:IaaS' %}",
        data: {'uri':'/cdn/v1/', 'api_key':$("#api_key").val(), 'access_key':$("#access_key").val(), 'secret_key':$("#secret_key").val(), 'query':$("#query").val(), 'url_list': list[key] },
        dataType: "json",
        success: function(data){
          $("#result_area").append("<div class='rescode' id='"+ key +"' onclick='slide("+ key +")' style='cursor:pointer'>" + list[key] + " : " + data.rescode  + "</div>");
          $("#result_area").append("<textarea class='result' id='pannel" + key + "'>" + data.result + "</textarea>");
        },error: function(request, status, error){
          alert(request.responseText);
        },
      });

        if(key===(list.length - 1)){
          $('.wrap-loading').addClass('display-none');
        }
      }
    }, 100);
  });

  function slide(key){
    $("#pannel" + key).slideToggle("slow");
  }

</script>
{% endblock content %}

check/templates/ncloud/iaas/cloudDB.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul><br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}" />
<div class="box">
  <div class="box-body">
    <div class="box-header with-border chk_hd" style="margin: 5px 5px 5px 10px">
      <div style="-webkit-flex:1; flex:1;"><h4>Cloud DB</h4></div>
      <div class="checks etrans chk_all" ><input type="checkbox" id="checkall" /><label for="checkall">모두선택</label></div>
    </div>

    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <form action="" method="POST">
              {% csrf_token %}
              <div style="margin: 10px 20px 20px 0px">
                <div class="chk_hd">
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="1" name="chk[]" value="getCloudDBConfigGroupList" /><label for="1">CloudDB Config group 조회</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="2" name="chk[]" value="getCloudDBImageProductList" /><label for="2">CloudDB 상품 리스트</label>
                    </div>
                    <div class="checks etrans chk_bd1">
                      <input type="checkbox" id="3" name="chk[]" value="getCloudDBProductListRequest" /><label for="3">CloudDB 이미지 상품 리스트</label>
                    </div>
                </div>

                <br/>

                <span class="recive">
                  Access Key &nbsp;&nbsp;&nbsp; <input type="text" name="access_key" id="access_key" placeholder="Access Key" value=" "/>
                  </span>
                  <span class="recive">
                    Secret Key &nbsp;&nbsp;&nbsp; <input type="text" name="secret_key" id="secret_key" placeholder="Secret Key" value=" "/>
                  </span><br><br>
                  <span class="recive">
                    API Key &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="api_key" id="api_key" placeholder="API Key" value=" " />
                    </span>&nbsp;&nbsp;&nbsp;
                  <span class="recive">
                    Query &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text" name="query" id="query" placeholder="Query string" value="   "/>
                  </span>
                <span class="recive"> &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="ui button huge" name="testBtn" id="testBtn" value="submit" style="height: 40px; width: 100px" />
                  </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>Cloud DB Result</h4><br>
    </div>

    <pre id="result_area">
      <div class="rescode" style="margin: 10px 0 0 10px; width:10px; height:10px;"></div>
    </pre>
  </div>
</div>

<div class="wrap-loading display-none" >
  <div class="loader"></div>
</div>

<script type="text/javascript">
$(document).ready( () => {
  $("#checkall").click( () => {
    if($("#checkall").prop("checked")){
      $("input[name='chk[]']").prop("checked", true);
    }else{
      $("input[name='chk[]']").prop("checked", false);
    }
  })
})

  $("#testBtn").click(function(){
    if ($("#api_key").val() == ""){
      alert("api_key 값을 입력해 주세요.");
      return $("#api_key").focus();
    }
    if ($("#access_key").val() == ""){
      alert("access_key 값을 입력해 주세요.");
      return $("#access_key").focus();
    }
    if ($("#secret_key").val() == ""){
      alert("secret_key 값을 입력해 주세요.");
      return $("#secret_key").focus();
    }
    if ( !$("input[name='chk[]']").is(":checked") ){
      console.log($("input[name='chk[]']").is(":checked"))
      alert("check.");
      return $("#checkall").focus();
    }

    var list = [];
    $("input[name='chk[]']:checked").each(function(){
      list.push($(this).val());
      $("#result_area").html("<div onclick='("+'$(".result").slideToggle("slow")'+")'>action : rescode ▼ </div><br/><br/>");
    })

    $('.wrap-loading').removeClass('display-none');

    setTimeout(function(){

      for (let key=0; key < list.length; key++){

      $.ajax({
        type: "POST",
        async: false,
        url: "{% url 'ncloud:IaaS' %}",
        data: {'uri':'/clouddb/v1/', 'api_key':$("#api_key").val(), 'access_key':$("#access_key").val(), 'secret_key':$("#secret_key").val(), 'query':$("#query").val(), 'url_list': list[key] },
        dataType: "json",
        success: function(data){
          $("#result_area").append("<div class='rescode' id='"+ key +"' onclick='slide("+ key +")' style='cursor:pointer'>" + list[key] + " : " + data.rescode  + "</div>");
          $("#result_area").append("<textarea class='result' id='pannel" + key + "'>" + data.result + "</textarea>");
        },error: function(request, status, error){
          alert(request.responseText);
        },
      });

        if(key===(list.length - 1)){
          $('.wrap-loading').addClass('display-none');
        }
      }
    }, 100);
  });

  function slide(key){
    $("#pannel" + key).slideToggle("slow");
  }

</script>
{% endblock content %}