check/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ncloud.views_ai_app import *
from ncloud.views_iaas import *
from ncloud.views import *
from ncloud.API_List import *

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [

    url(r'^api/$', index, name='index'),

    # AI / Application
    url(r'^CSS$', CSS, name='CSS'),
    url(r'^nShortURLTest$', nShortURLTest, name='nShortURLTest'),
    url(r'^mapsTest$', mapsTest, name='mapsTest'),

    url(r'^api/ai_clova$', Clova, name='Clova'),
    url(r'^api/Maps$', Maps, name='Maps'),
    url(r'^api/Papago$', Papago, name='Papago'),
    url(r'^api/nShortURL$', nShortURL, name='nShortURL'),
    url(r'^api/CAPTCHA$', CAPTCHA, name='CAPTCHA'),
    url(r'^api/CAPTCHA_Check$', CAPTCHA_Check, name='CAPTCHA_Check'),
    url(r'^api/SearchTrend$', SearchTrend, name='SearchTrend'),
    url(r'^api/APIGW/$', APIGW, name='APIGW'),

    # PasS
    url(r'^api/geoLocation/$', geoLocation, name='geoLocation'),

    # IaaS
    url(r'^api/(?P<category>[a-z]+)/(?P<service>[a-zA-Z]+)/$', ServiceUrl, name='ServiceUrl'),
    url(r'^api/IaaS$', IaaS, name='IaaS'),

    # URL List
    url(r'^api/IaaS_API$', IaaS_API, name='IaaS_API'),
    url(r'^api/PaaS_API$', PaaS_API, name='PaaS_API'),
    url(r'^api/App_API$', App_API, name='App_API'),

]

learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learning_log.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^ncloud/', include('check.urls', namespace='ncloud')),
]

check/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models


class NaverApiStatus(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_type = models.CharField(max_length=20, blank=True, null=True)
    api_status = models.IntegerField(blank=True, null=True)
    api_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_status'


class NaverApiErrorLog(models.Model):
    api_seq = models.AutoField(primary_key=True)
    api_name = models.CharField(max_length=70, blank=True, null=True)
    api_error_code = models.CharField(max_length=50, blank=True, null=True)
    api_error_time = models.DateTimeField(blank=True, null=True)

    class Meta:
#        managed = False
        db_table = 'naver_api_error_log'

check/views.py
from django.shortcuts import render
from django.http import HttpResponse
from urllib.error import HTTPError, URLError
from django.views.decorators.csrf import csrf_exempt
import os, sys, ast, json, time, base64, hmac, hashlib
import urllib.request


@csrf_exempt
def ServiceUrl(request, category, service):
    return render(request, 'ncloud/' + category + '/' + service + '.html')

@csrf_exempt
def Hmac_Ajax(request, uri):
    timestamp = int(time.time() * 1000)
    timestamp = str(timestamp)
    api_key = request.POST.get("api_key")
    access_key = request.POST.get("access_key")
    secret_key = request.POST.get("secret_key")
    secret_key = bytes(secret_key, 'UTF-8')

    method = "GET"
    if uri == '/api-test/v1/api':
        url = "https://ta50do4nv5.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + access_key
        sig = "x-ncp-apigw-signature-v2"
    else:
        url = "https://ncloud.apigw.ntruss.com" + uri
        message = method + " " + uri + "\n" + timestamp + "\n" + api_key + "\n" + access_key
        sig = "x-ncp-apigw-signature-v1"
    message = bytes(message, 'UTF-8')
    signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
    sig_key = signingKey.decode('utf-8')

    req = urllib.request.Request(url)
    req.add_header("X-ncp-apigw-timestamp", timestamp)
    req.add_header("x-ncp-apigw-api-key", api_key)
    req.add_header("x-ncp-iam-access-key", access_key)
    req.add_header(sig, sig_key)
    res = urllib.request.urlopen(req)

    return res


@csrf_exempt
def App_Ajax(request, url):
    client_id = request.POST.get("client_id")
    client_secret = request.POST.get("client_secret")
    req = urllib.request.Request(url)
    req.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    req.add_header("X-NCP-APIGW-API-KEY",client_secret)
    return req


@csrf_exempt
def IaaS(request):
    rescode = "잘못된 method 입니다."
    rtnVal = {'rescode': rescode}
    if request.method=='POST':
        uri = request.POST.get("uri")
        api_list = request.POST.get("url_list")

        if request.POST.get("query") == None:
            qstring = ""
        else:
            qstring = request.POST.get("query")

        if '?' in api_list:
            queryCon = "&"
        else:
            queryCon = "?"
        uri = uri + api_list + queryCon + 'responseFormatType=json&' + qstring

        url = 'https://ncloud.apigw.ntruss.com' + uri
        try:
            res = Hmac_Ajax(request, uri)
        except URLError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        except HTTPError as e:
            rescode = "client_id 또는 client_secret 값을 확인해 주세요"
        else:
            rescode = res.getcode()
        if(rescode == 200):
            response_body = res.read()
            result = response_body.decode()
            result = result[2:-1]
            rtnVal = {"rescode": rescode, "result": result}
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
        else:
            rtnVal = {"rescode": rescode}
            print("Error Code:" + rescode)
            return HttpResponse(json.dumps(rtnVal), content_type='application/json')
    else:
        return HttpResponse(json.dumps(rtnVal), content_type='application/json')

check/templates/ncloud/api_list.html
{% load bootstrap3 %}

<!-- api 리스트 드롭다운 iaas / paas / ai·application   ㄱ한자 탭 8-->

<style>
.dropdown-toggle{
  font-size: 20px;
  color: #517d98;
}
.dropdown-item{
  font-size: 16px;
  color: #517d98;
}
</style>

<script type="text/javascript">
$(document).ready( () => {
  $(".disabled").on("click", () => {
    alert(" 오픈예정입니다. ");
  })
})
</script>

<div class="panel">
  <section id="platform">
    <div class="ui pointing menu">

      <span class="dropdown">
        <a class="dropdown-toggle item" data-toggle="dropdown" href="#"> AI·Application &nbsp;
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="dropdown-item"><a href="/ncloud/api/ai_clova">Clova</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/Maps">Maps</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/Papago">Papago</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/nShortURL">nShortURL</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/CAPTCHA">CAPTCHA</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/SearchTrend">SearchTrend</a></li>
          <li class="dropdown-item"><a href="/ncloud/api/APIGW">API Gateway</a></li>
        </ul>
      </span>

      <span class="dropdown">
        <a class="dropdown-toggle item" data-toggle="dropdown" href="#"> IaaS &nbsp;
        <span class="caret"></span></a>
        <ul class="dropdown-menu">

          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='server' %}">Server (15)</a></li>
          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='lb' %}">Load Balancing (2)</a></li>
          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='autoscaling' %}">Auto Scaling (8)</a></li>
          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='monitoring' %}">Monitoring (2)</a></li>
          <!-- li class="dropdown-item disabled"><a href="#">Security (1)</a></li -->
          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='cdn' %}">CDN (2)</a></li>
          <li class="dropdown-item"><a href="{% url 'ncloud:ServiceUrl' category='iaas' service='cloudDB' %}">Cloud DB (3)</a></li>
        </ul>
      </span>

      <span class="dropdown">
        <a class="dropdown-toggle item" data-toggle="dropdown" href="#"> PaaS &nbsp;
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="dropdown-item"><a href="/ncloud/api/geoLocation">GeoLocation</a></li>
          <!-- li class="dropdown-item disabled"><a href="#">Cloud Outbound Mailer</a></li -->
          <!-- li class="dropdown-item disabled"><a href="/ncloud/api/">test</a></li -->
        </ul>
      </span>

    </div>
  </section>
</div>

check/templates/ncloud/index.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block page_name %}&nbsp;<a href="{% url 'ncloud:index' %}">Ncloud API Check</a>{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
  <li>Dashboard</li>
  <li>NCP API</li>
</ul>
<br>
{% endblock breadcrumbs %}
{% block content %}
{% include 'ncloud/api_list.html' %}

<div class="box">
  <div class="box-body">
    <div class="box-header with-border">
      <h4>NCP Application API</h4></div>
    <div class="box-body">
      <div class="dataTables_wrapper form-inline dt-bootstrap no-footer" id="datatables-example_wrapper">
        <div class="row">
          <div class="col-sm-12">
            <a href="http://docs.ncloud.com/ko/naveropenapi_v2/naveropenapi-2-2.html">NCP Application API Check</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="box">
    <div class="box-body">
      <div class="box-header with-border">
        <h4>현재 각 API 작동 상태</h4>
      </div>

<div style="padding-left:0.5%; padding-right:0.5%;">
<pre>
<img src='/media/i_green.png' />  현재 정상 작동중입니다.
<img src='/media/i_yellow.png' />  API서버 과부하로 인하여 응답이 지연되고 있습니다.
<img src='/media/i_red.png' />  API에서 오류가 발생하였습니다.
</pre>
</div>

    </div>
    <div class='padding'>
    <table id="myTable" class="table table-striped table-bordered no-footer" >
      <div class="row">
        <thea>
          <tr role="row">
            <th class='center hd'>상태</th>
            <th class='hd'>API URL</th>
            <th class='hd'>API 명</th>
            <th class='hd'>업데이트 시각</th>
        </thead>
        <tbody>
          {% for i in data %}
          <tr id='tr{{i.api_seq}}'>
            <td id='s{{i.api_seq}}' class='center bd'>{{i.api_status}}</td>
            <td id='n{{i.api_seq}}' class='bd'>{{i.api_name}}</td>
            <td class='bd aa'>{{i.api_type}}</td>
            {# <td>{{i.api_time }}</td> #}
            <td class='bd'>{{i.api_time| date:"Y-m-d H:i:s" }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </div>
    </table>
  </div>
</div>

<style media="screen">
  .padding{
    padding-top: 10px; padding-right: 1%; padding-left: 1%; padding-bottom: 10px;
  }
  .center{
    text-align:center;
  }
  .hd{
    height: 34px;
    background-color: #f5f5f6;
    border: 0;
    border-top: 1px solid #e8e8ea;
    border-bottom: 1px solid #e8e8ea;
    color: #343434;
    text-align: center;
    font-weight: bold;
    word-break: break-all;
    vertical-align: middle;
    font-size: 15px;
    line-height: 2.0;
  }
  .bd{
    text-align:center;
    padding: 18px 0;
    border: 0;
    border-bottom: 1px solid #e8e8ea;
    color: #323332;
    word-break: break-all;
    font-size: 13.5px;
    font-weight: normal;
    font-style: normal;
    font-stretch: normal;
    line-height: 1.6;
    letter-spacing: -0.4px;
  }
</style>

<script src="{% static 'js/table-sort.js' %}" ></script>
<script type="text/javascript">
  $(document).ready( () => {
      sortTable(0)
      for(let i=1; i<={{ data|length }}; i++){
          var td = document.getElementById('n'+i).innerHTML
          var text = td.replace(/[-]/g, '/')
          // var text = test.replace(/zh[\-]CN/g, '/')
          text = text.replace('zh/CN', 'zh-CN')
          text = text.replace('zh/TW', 'zh-TW')
          document.getElementById('n'+i).innerHTML = text

          // $("#s"+i).text().sort( (a,b) => b-a )

          if ($("#s"+i).text() == 0){
            $("#s"+i).html("<img src='/media/i_green.png' />")
            // $("#tr"+i).addClass('alert alert-success')
            // document.getElementById("tr"+i).style.backgroundColor="#dff0d8"
          }
          else{
            $("#s"+i).html("<img src='/media/i_red.png' />")
            // document.getElementById("tr"+i).style.backgroundColor="#f2dede"
          }
      }

  })
</script>

{% endblock content %}